name: Publish prem mock images
on: {push: {branches: [main]}}
jobs:
  push-mocks:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v3
    - id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Build & push prem
      run:  >-
        docker buildx build --push
        --file ./resources/mocks/generic/Dockerfile
        --tag ghcr.io/premai-io/chat-mock-small:0.0.1
        --tag ghcr.io/premai-io/chat-mock-small:latest
        --tag ghcr.io/premai-io/chat-mock-medium:0.0.1
        --tag ghcr.io/premai-io/chat-mock-medium:latest
        --tag ghcr.io/premai-io/chat-mock-large:0.0.1
        --tag ghcr.io/premai-io/chat-mock-large:latest
        --tag ghcr.io/premai-io/embeddings-mock-small:0.0.1
        --tag ghcr.io/premai-io/embeddings-mock-small:latest
        --tag ghcr.io/premai-io/embeddings-mock-medium:0.0.1
        --tag ghcr.io/premai-io/embeddings-mock-medium:latest
        --tag ghcr.io/premai-io/embeddings-mock-large:0.0.1
        --tag ghcr.io/premai-io/embeddings-mock-large:latest
        --platform linux/arm64,linux/amd64 ./resources/mocks/generic
