name: CI
on:
  pull_request:
jobs:
  test:
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_CLI_EXPERIMENTAL: enabled
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create the .env file from example
      run: cp .env.example .env
    - name: Build the Stack
      run: docker-compose build
    - name: Run APIs Tests
      run: docker-compose run premd pytest
    - name: Tear down the Stack
      run: docker-compose down
