name: Publish prem docker image
on: {push: {tags: ['*']}}
jobs:
  push:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Build & push prem
      run:  >-
        docker buildx build --push
        --file Dockerfile
        --tag ghcr.io/premai-io/premd:latest
        --tag ghcr.io/premai-io/premd:"${GITHUB_REF#refs/tags/}"
        --platform linux/arm64,linux/amd64 .
    - name: Release
      run: gh release create --generate-notes "${GITHUB_REF#refs/tags/}"
      env:
        GH_TOKEN: ${{ github.token }}
